#!/bin/sh
set -o errexit
set -o nounset

uv sync --frozen
uv run watchfiles --filter default "celery -A config.celery_app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler" /app/lukasz_pudlo /app/config
